# Capstone Final Project

### Creating the Dataframe

In [1]:
# Importing Pandas and NumPy and preventing a warning message
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

In [2]:
# Scraping the table from the website
url = "https://en.wikipedia.org/wiki/List_of_London_boroughs"
dfs = pd.read_html(url)

print(len(dfs))

5

In [3]:
# Converting the table into a Dataframe
df = dfs[0]
df

,Borough,Inner,Status,Local authority,Political control,Headquarters,Area (sq mi),Population (2019 est)[1],Co-ordinates,Nr. in map
0,Barking and Dagenham [note 1],NaN,NaN,Barking and Dagenham London Borough Council,Labour,"Town Hall, 1 Town Square",13.93,212906,".mw-parser-output .geo-default,.mw-parser-outp...",25
1,Barnet,NaN,NaN,Barnet London Borough Council,Conservative,"Barnet House, 2 Bristol Avenue, Colindale",33.49,395896,51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W,31
2,Bexley,NaN,NaN,Bexley London Borough Council,Conservative,"Civic Offices, 2 Watling Street",23.38,248287,51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E,23
3,Brent,NaN,NaN,Brent London Borough Council,Labour,"Brent Civic Centre, Engineers Way",16.70,329771,51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W,12
4,Bromley,NaN,NaN,Bromley London Borough Council,Conservative,"Civic Centre, Stockwell Close",57.97,332336,51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E,20
5,Camden,NaN,NaN,Camden London Borough Council,Labour,"Camden Town Hall, Judd Street",8.40,270029,51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W,11
6,Croydon,NaN,NaN,Croydon London Borough Council,Labour,"Bernard Weatherill House, Mint Walk",33.41,386710,51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W,19
7,Ealing,NaN,NaN,Ealing London Borough Council,Labour,"Perceval House, 14-16 Uxbridge Road",21.44,341806,51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W,13
8,Enfield,NaN,NaN,Enfield London Borough Council,Labour,"Civic Centre, Silver Street",31.74,333794,51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W,30
9,Greenwich [note 2],[note 3],Royal,Greenwich London Borough Council,Labour,"Woolwich Town Hall, Wellington Street",18.28,287942,51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E,22
10,Hackney,NaN,NaN,Hackney London Borough Council,Labour,"Hackney Town Hall, Mare Street",7.36,281120,51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W,9
11,Hammersmith and Fulham [note 4],NaN,NaN,Hammersmith and Fulham London Borough Council,Labour,"Town Hall, King Street",6.33,185143,51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W,4
12,Haringey,[note 3],NaN,Haringey London Borough Council,Labour,"Civic Centre, High Road",11.42,268647,51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W,29
13,Harrow,NaN,NaN,Harrow London Borough Council,Labour,"Civic Centre, Station Road",19.49,251160,51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W,32
14,Havering,NaN,NaN,Havering London Borough Council,Conservative (council NOC),"Town Hall, Main Road",43.35,259552,51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E,24
15,Hillingdon,NaN,NaN,Hillingdon London Borough Council,Conservative,"Civic Centre, High Street",44.67,306870,51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W,33
16,Hounslow,NaN,NaN,Hounslow London Borough Council,Labour,"Hounslow House, 7 Bath Road",21.61,271523,51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W,14
17,Islington,NaN,NaN,Islington London Borough Council,Labour,"Customer Centre, 222 Upper Street",5.74,242467,51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W,10
18,Kensington and Chelsea,NaN,Royal,Kensington and Chelsea London Borough Council,Conservative,"The Town Hall, Hornton Street",4.68,156129,51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W,3
19,Kingston upon Thames,NaN,Royal,Kingston upon Thames London Borough Council,Liberal Democrat,"Guildhall, High Street",14.38,177507,51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W,16
20,Lambeth,NaN,NaN,Lambeth London Borough Council,Labour,"Lambeth Town Hall, Brixton Hill",10.36,326034,51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W,6
21,Lewisham,NaN,NaN,Lewisham London Borough Council,Labour,"Town Hall, 1 Catford Road",13.57,305842,51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W,21
22,Merton,NaN,NaN,Merton London Borough Council,Labour,"Civic Centre, London Road",14.52,206548,51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W,17
23,Newham,[note 3],NaN,Newham London Borough Council,Labour,"Newham Dockside, 1000 Dockside Road",13.98,353134,51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E,27
24,Redbridge,NaN,NaN,Redbridge London Borough Council,Labour,"Town Hall, 128-142 High Road",21.78,305222,51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E,26
25,Richmond upon Thames,NaN,NaN,Richmond upon Thames London Borough Council,Liberal Democrat,"Civic Centre, 44 York Street",22.17,198019,51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W,15
26,Southwark,NaN,NaN,Southwark London Borough Council,Labour,160 Tooley Street,11.14,318830,51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W,7
27,Sutton,NaN,NaN,Sutton London Borough Council,Liberal Democrat,"Civic Offices, St Nicholas Way",16.93,206349,51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W,18
28,Tower Hamlets,NaN,NaN,Tower Hamlets London Borough Council,Labour,"Town Hall, Mulberry Place, 5 Clove Crescent",7.63,324745,51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W,8
29,Waltham Forest,NaN,NaN,Waltham Forest London Borough Council,Labour,"Waltham Forest Town Hall, Forest Road",14.99,276983,51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W,28
30,Wandsworth,NaN,NaN,Wandsworth London Borough Council,Conservative,"The Town Hall, Wandsworth High Street",13.23,329677,51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W,5
31,Westminster,NaN,City,Westminster City Council,Conservative,"Westminster City Hall, 64 Victoria Street",8.29,261317,51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W,2

### Cleaning the Dataframe

In [4]:
# Only taking the columns of interest
df = df[["Borough", "Co-ordinates"]]
df

,Borough,Co-ordinates
0,Barking and Dagenham [note 1],".mw-parser-output .geo-default,.mw-parser-outp..."
1,Barnet,51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W
2,Bexley,51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E
3,Brent,51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W
4,Bromley,51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E
5,Camden,51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W
6,Croydon,51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W
7,Ealing,51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W
8,Enfield,51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W
9,Greenwich [note 2],51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E
10,Hackney,51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W
11,Hammersmith and Fulham [note 4],51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W
12,Haringey,51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W
13,Harrow,51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W
14,Havering,51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E
15,Hillingdon,51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W
16,Hounslow,51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W
17,Islington,51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W
18,Kensington and Chelsea,51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W
19,Kingston upon Thames,51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W
20,Lambeth,51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W
21,Lewisham,51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W
22,Merton,51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W
23,Newham,51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E
24,Redbridge,51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E
25,Richmond upon Thames,51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W
26,Southwark,51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W
27,Sutton,51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W
28,Tower Hamlets,51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W
29,Waltham Forest,51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W
30,Wandsworth,51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W
31,Westminster,51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W

In [5]:
# Dropping the first row as there are no coordinate values
df.drop([0], inplace = True)
df.reset_index(drop = True, inplace = True)
df

,Borough,Co-ordinates
0,Barnet,51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W
1,Bexley,51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E
2,Brent,51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W
3,Bromley,51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E
4,Camden,51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W
5,Croydon,51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W
6,Ealing,51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W
7,Enfield,51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W
8,Greenwich [note 2],51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E
9,Hackney,51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W
10,Hammersmith and Fulham [note 4],51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W
11,Haringey,51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W
12,Harrow,51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W
13,Havering,51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E
14,Hillingdon,51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W
15,Hounslow,51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W
16,Islington,51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W
17,Kensington and Chelsea,51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W
18,Kingston upon Thames,51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W
19,Lambeth,51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W
20,Lewisham,51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W
21,Merton,51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W
22,Newham,51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E
23,Redbridge,51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E
24,Richmond upon Thames,51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W
25,Southwark,51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W
26,Sutton,51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W
27,Tower Hamlets,51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W
28,Waltham Forest,51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W
29,Wandsworth,51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W
30,Westminster,51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W

In [6]:
# Removing the unnecessary 'notes' in the Borough names
df.replace({"Borough": {"Greenwich [note 2]": "Greenwich", 
                        "Hammersmith and Fulham [note 4]": "Hammersmith and Fulham"}}, inplace = True)
df

                   Borough                                 Co-ordinates
0                   Barnet  51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W
1                   Bexley  51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E
2                    Brent  51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W
3                  Bromley  51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E
4                   Camden  51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W
5                  Croydon  51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W
6                   Ealing  51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W
7                  Enfield  51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W
8                Greenwich  51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E
9                  Hackney  51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W
10  Hammersmith and Fulham  51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W
11                Haringey  51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W
12                  Harrow  51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W
13                Havering  51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E
14              Hillingdon  51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W
15                Hounslow  51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W
16               Islington  51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W
17  Kensington and Chelsea  51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W
18    Kingston upon Thames  51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W
19                 Lambeth  51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W
20                Lewisham  51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W
21                  Merton  51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W
22                  Newham  51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E
23               Redbridge  51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E
24    Richmond upon Thames  51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W
25               Southwark  51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W
26                  Sutton  51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W
27           Tower Hamlets  51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W
28          Waltham Forest  51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W
29              Wandsworth  51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W
30             Westminster  51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W

In [7]:
# Splitting the coordinates column to only have the needed values
df[["LatLong1", "LatLong2"]] = df["Co-ordinates"].str.split("/", expand = True)
df = df[["Borough", "LatLong2"]]
df

                   Borough              LatLong2
0                   Barnet   ﻿51.6252°N 0.1517°W
1                   Bexley   ﻿51.4549°N 0.1505°E
2                    Brent   ﻿51.5588°N 0.2817°W
3                  Bromley   ﻿51.4039°N 0.0198°E
4                   Camden   ﻿51.5290°N 0.1255°W
5                  Croydon   ﻿51.3714°N 0.0977°W
6                   Ealing   ﻿51.5130°N 0.3089°W
7                  Enfield   ﻿51.6538°N 0.0799°W
8                Greenwich   ﻿51.4892°N 0.0648°E
9                  Hackney   ﻿51.5450°N 0.0553°W
10  Hammersmith and Fulham   ﻿51.4927°N 0.2339°W
11                Haringey   ﻿51.6000°N 0.1119°W
12                  Harrow   ﻿51.5898°N 0.3346°W
13                Havering   ﻿51.5812°N 0.1837°E
14              Hillingdon   ﻿51.5441°N 0.4760°W
15                Hounslow   ﻿51.4746°N 0.3680°W
16               Islington   ﻿51.5416°N 0.1022°W
17  Kensington and Chelsea   ﻿51.5020°N 0.1947°W
18    Kingston upon Thames   ﻿51.4085°N 0.3064°W
19                 Lambeth   ﻿51.4607°N 0.1163°W
20                Lewisham   ﻿51.4452°N 0.0209°W
21                  Merton   ﻿51.4014°N 0.1958°W
22                  Newham   ﻿51.5077°N 0.0469°E
23               Redbridge   ﻿51.5590°N 0.0741°E
24    Richmond upon Thames   ﻿51.4479°N 0.3260°W
25               Southwark   ﻿51.5035°N 0.0804°W
26                  Sutton   ﻿51.3618°N 0.1945°W
27           Tower Hamlets   ﻿51.5099°N 0.0059°W
28          Waltham Forest   ﻿51.5908°N 0.0134°W
29              Wandsworth   ﻿51.4567°N 0.1910°W
30             Westminster   ﻿51.4973°N 0.1372°W

In [8]:
# Splitting the LatLong2 column into separate latitude and longitude columns
df1 = df["LatLong2"].str.split(" ", expand = True)
df1.columns = ["LongLat{}".format(x) for x in df1.columns]
df = df.join(df1)
df = df[["Borough", "LongLat1", "LongLat2"]]

# Renaming the columns
df.rename(columns = {"LongLat1": "Latitude", 
                     "LongLat2": "Longitude"}, inplace  = True)
df

                   Borough    Latitude Longitude
0                   Barnet  ﻿51.6252°N  0.1517°W
1                   Bexley  ﻿51.4549°N  0.1505°E
2                    Brent  ﻿51.5588°N  0.2817°W
3                  Bromley  ﻿51.4039°N  0.0198°E
4                   Camden  ﻿51.5290°N  0.1255°W
5                  Croydon  ﻿51.3714°N  0.0977°W
6                   Ealing  ﻿51.5130°N  0.3089°W
7                  Enfield  ﻿51.6538°N  0.0799°W
8                Greenwich  ﻿51.4892°N  0.0648°E
9                  Hackney  ﻿51.5450°N  0.0553°W
10  Hammersmith and Fulham  ﻿51.4927°N  0.2339°W
11                Haringey  ﻿51.6000°N  0.1119°W
12                  Harrow  ﻿51.5898°N  0.3346°W
13                Havering  ﻿51.5812°N  0.1837°E
14              Hillingdon  ﻿51.5441°N  0.4760°W
15                Hounslow  ﻿51.4746°N  0.3680°W
16               Islington  ﻿51.5416°N  0.1022°W
17  Kensington and Chelsea  ﻿51.5020°N  0.1947°W
18    Kingston upon Thames  ﻿51.4085°N  0.3064°W
19                 Lambeth  ﻿51.4607°N  0.1163°W
20                Lewisham  ﻿51.4452°N  0.0209°W
21                  Merton  ﻿51.4014°N  0.1958°W
22                  Newham  ﻿51.5077°N  0.0469°E
23               Redbridge  ﻿51.5590°N  0.0741°E
24    Richmond upon Thames  ﻿51.4479°N  0.3260°W
25               Southwark  ﻿51.5035°N  0.0804°W
26                  Sutton  ﻿51.3618°N  0.1945°W
27           Tower Hamlets  ﻿51.5099°N  0.0059°W
28          Waltham Forest  ﻿51.5908°N  0.0134°W
29              Wandsworth  ﻿51.4567°N  0.1910°W
30             Westminster  ﻿51.4973°N  0.1372°W

In [9]:
# Removing the unnecessary '°N' from the latitude values
df["Latitude"] = df["Latitude"].str.rstrip("°N")
df

                   Borough  Latitude Longitude
0                   Barnet  ﻿51.6252  0.1517°W
1                   Bexley  ﻿51.4549  0.1505°E
2                    Brent  ﻿51.5588  0.2817°W
3                  Bromley  ﻿51.4039  0.0198°E
4                   Camden  ﻿51.5290  0.1255°W
5                  Croydon  ﻿51.3714  0.0977°W
6                   Ealing  ﻿51.5130  0.3089°W
7                  Enfield  ﻿51.6538  0.0799°W
8                Greenwich  ﻿51.4892  0.0648°E
9                  Hackney  ﻿51.5450  0.0553°W
10  Hammersmith and Fulham  ﻿51.4927  0.2339°W
11                Haringey  ﻿51.6000  0.1119°W
12                  Harrow  ﻿51.5898  0.3346°W
13                Havering  ﻿51.5812  0.1837°E
14              Hillingdon  ﻿51.5441  0.4760°W
15                Hounslow  ﻿51.4746  0.3680°W
16               Islington  ﻿51.5416  0.1022°W
17  Kensington and Chelsea  ﻿51.5020  0.1947°W
18    Kingston upon Thames  ﻿51.4085  0.3064°W
19                 Lambeth  ﻿51.4607  0.1163°W
20                Lewisham  ﻿51.4452  0.0209°W
21                  Merton  ﻿51.4014  0.1958°W
22                  Newham  ﻿51.5077  0.0469°E
23               Redbridge  ﻿51.5590  0.0741°E
24    Richmond upon Thames  ﻿51.4479  0.3260°W
25               Southwark  ﻿51.5035  0.0804°W
26                  Sutton  ﻿51.3618  0.1945°W
27           Tower Hamlets  ﻿51.5099  0.0059°W
28          Waltham Forest  ﻿51.5908  0.0134°W
29              Wandsworth  ﻿51.4567  0.1910°W
30             Westminster  ﻿51.4973  0.1372°W

In [10]:
# Adjusting the longitude values so they are in the correct format
london_df = df

london_df["Longitude"] = london_df["Longitude"].str.rstrip("°W")
london_df["Longitude"] = np.where(london_df["Longitude"].str.len() == 6, 
                                  "-" + london_df["Longitude"], 
                                  london_df["Longitude"].str.rstrip("°E"))

london_df

                   Borough  Latitude Longitude
0                   Barnet  ﻿51.6252   -0.1517
1                   Bexley  ﻿51.4549    0.1505
2                    Brent  ﻿51.5588   -0.2817
3                  Bromley  ﻿51.4039    0.0198
4                   Camden  ﻿51.5290   -0.1255
5                  Croydon  ﻿51.3714   -0.0977
6                   Ealing  ﻿51.5130   -0.3089
7                  Enfield  ﻿51.6538   -0.0799
8                Greenwich  ﻿51.4892    0.0648
9                  Hackney  ﻿51.5450   -0.0553
10  Hammersmith and Fulham  ﻿51.4927   -0.2339
11                Haringey  ﻿51.6000   -0.1119
12                  Harrow  ﻿51.5898   -0.3346
13                Havering  ﻿51.5812    0.1837
14              Hillingdon  ﻿51.5441   -0.4760
15                Hounslow  ﻿51.4746   -0.3680
16               Islington  ﻿51.5416   -0.1022
17  Kensington and Chelsea  ﻿51.5020   -0.1947
18    Kingston upon Thames  ﻿51.4085   -0.3064
19                 Lambeth  ﻿51.4607   -0.1163
20                Lewisham  ﻿51.4452   -0.0209
21                  Merton  ﻿51.4014   -0.1958
22                  Newham  ﻿51.5077    0.0469
23               Redbridge  ﻿51.5590    0.0741
24    Richmond upon Thames  ﻿51.4479   -0.3260
25               Southwark  ﻿51.5035   -0.0804
26                  Sutton  ﻿51.3618   -0.1945
27           Tower Hamlets  ﻿51.5099   -0.0059
28          Waltham Forest  ﻿51.5908   -0.0134
29              Wandsworth  ﻿51.4567   -0.1910
30             Westminster  ﻿51.4973   -0.1372

In [11]:
# Removing hidden byte order mark from web scraping
london_df["Latitude"] = london_df["Latitude"].str.replace(u"\ufeff", "")
london_df["Longitude"] = london_df["Longitude"].str.replace(u"\ufeff", "")

### Creating a map to visualise the Boroughs

In [12]:
# Importing the necessary programs to make the map
from geopy.geocoders import Nominatim
import folium
import requests

In [13]:
# Getting the latitude and longitude values of London
geolocator = Nominatim(user_agent = "london_explorer")
location = geolocator.geocode("London, UK")
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinates of London are {}, {}.'.format(latitude, longitude))

The geograpical coordinates of London are 51.5073219, -0.1276474.

In [14]:
#Producing a map of London using the latitude and longitude values
map_london = folium.Map(location = [latitude, longitude], zoom_start = 10)

# Marking all the Boroughs on the map
for lat, lng, borough in zip(london_df["Latitude"], london_df["Longitude"], london_df["Borough"]):
    label = "{}".format(borough)
    label = folium.Popup(label, parse_html = True)
    folium.CircleMarker([lat, lng], 
                        radius = 5, 
                        popup = label, 
                        color = "blue", 
                        fill = True, 
                        fill_color = "3186cc", 
                        fill_opacity = 0.7, 
                        parse_html = False).add_to(map_london)

map_london

In [15]:
# This cell contained Foursquare ID and secret

### Using the Foursquare data to get information on venues within the Boroughs

In [16]:
# Creating a function to get venue information for all the Boroughs
def getNearbyVenues(boroughs, latitudes, longitudes, radius = 1000):
    
    venues_list = []
    for borough, lat, lng in zip(boroughs, latitudes, longitudes):
        print(borough)
        
        url = "https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}".format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
        
        results = requests.get(url).json()["response"]["groups"][0]["items"]
        
        venues_list.append([(
            borough, 
            lat, 
            lng, 
            v["venue"]["name"], 
            v["venue"]["location"]["lat"], 
            v["venue"]["location"]["lng"], 
            v["venue"]["categories"][0]["name"]) for v in results])
        
    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ["Borough", 
                             "Borough Latitude", 
                             "Borough Longitude", 
                             "Venue", 
                             "Venue Latitude", 
                             "Venue Longitude", 
                             "Venue Category"]
    
    return(nearby_venues)

In [17]:
# Creating a new Dataframe with this information
london_venues = getNearbyVenues(boroughs = london_df["Borough"], 
                                latitudes = london_df["Latitude"], 
                                longitudes = london_df["Longitude"])
london_venues

Barnet
Bexley
Brent
Bromley
Camden
Croydon
Ealing
Enfield
Greenwich
Hackney
Hammersmith and Fulham
Haringey
Harrow
Havering
Hillingdon
Hounslow
Islington
Kensington and Chelsea
Kingston upon Thames
Lambeth
Lewisham
Merton
Newham
Redbridge
Richmond upon Thames
Southwark
Sutton
Tower Hamlets
Waltham Forest
Wandsworth
Westminster

,Borough,Borough Latitude,Borough Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Barnet,51.6252,-0.1517,The Cavalier,51.629646,-0.157798,Pub
1,Barnet,51.6252,-0.1517,The Atrium,51.624726,-0.151933,Café
2,Barnet,51.6252,-0.1517,Beaconsfield Road (BF),51.622827,-0.151466,Bus Stop
3,Barnet,51.6252,-0.1517,The Osidge Arms,51.631986,-0.143123,Pub
4,Barnet,51.6252,-0.1517,Tesco Express,51.625944,-0.160032,Grocery Store
...,...,...,...,...,...,...,...
2188,Westminster,51.4973,-0.1372,The Queens Arms,51.492567,-0.139297,Pub
2189,Westminster,51.4973,-0.1372,Upper Grosvenor Gardens,51.497802,-0.147046,Park
2190,Westminster,51.4973,-0.1372,Grays of Westminster,51.491336,-0.138983,Camera Store
2191,Westminster,51.4973,-0.1372,Winston Churchill Statue,51.500799,-0.126267,Outdoor Sculpture
2192,Westminster,51.4973,-0.1372,Rosa's Thai Cafe,51.493732,-0.141673,Thai Restaurant

In [18]:
# The number of unique types of venues
print("There are {} unique categories".format(len(london_venues["Venue Category"].unique())))

# The number of venues per Borough
london_venues.groupby("Borough").count()

There are 258 unique categories

,Borough Latitude,Borough Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Borough,,,,,,
Barnet,8,8,8,8,8,8
Bexley,47,47,47,47,47,47
Brent,90,90,90,90,90,90
Bromley,62,62,62,62,62,62
Camden,100,100,100,100,100,100
Croydon,96,96,96,96,96,96
Ealing,100,100,100,100,100,100
Enfield,63,63,63,63,63,63
Greenwich,58,58,58,58,58,58
Hackney,79,79,79,79,79,79
Hammersmith and Fulham,100,100,100,100,100,100
Haringey,68,68,68,68,68,68
Harrow,42,42,42,42,42,42
Havering,76,76,76,76,76,76
Hillingdon,72,72,72,72,72,72
Hounslow,66,66,66,66,66,66
Islington,100,100,100,100,100,100
Kensington and Chelsea,100,100,100,100,100,100
Kingston upon Thames,100,100,100,100,100,100
Lambeth,100,100,100,100,100,100
Lewisham,39,39,39,39,39,39
Merton,29,29,29,29,29,29
Newham,38,38,38,38,38,38
Redbridge,45,45,45,45,45,45
Richmond upon Thames,77,77,77,77,77,77
Southwark,100,100,100,100,100,100
Sutton,51,51,51,51,51,51
Tower Hamlets,73,73,73,73,73,73
Waltham Forest,39,39,39,39,39,39
Wandsworth,75,75,75,75,75,75
Westminster,100,100,100,100,100,100

### Analysing the Boroughs

The countries defined as 'East Asian' (China, Hong Kong, Japan, Macau, Mongolia, North Korea, South Korea and Taiwan) would be expected to have similar cuisines to that in South Korea.

In [19]:
# Getting all the unique venue categories to separate out the 'East Asian' restaurants
print(london_venues["Venue Category"].unique())

['Pub' 'Café' 'Bus Stop' 'Grocery Store' 'Park' 'Fish & Chips Shop'
 'Italian Restaurant' 'Furniture / Home Store' 'Clothing Store'
 'American Restaurant' 'Hotel' 'Plaza' 'Pharmacy' 'Department Store'
 'Supermarket' 'Bakery' 'Coffee Shop' 'Video Game Store'
 'Portuguese Restaurant' 'Pizza Place' 'Fast Food Restaurant'
 'Chinese Restaurant' 'Warehouse Store' 'Shopping Mall' 'Restaurant'
 'Mexican Restaurant' 'Bus Station' 'Burger Joint'
 'Mediterranean Restaurant' 'Nightclub' 'Greek Restaurant' 'Playground'
 'Bowling Alley' 'Stadium' 'Chocolate Shop' 'Outdoor Sculpture'
 'Food Court' 'Music Venue' 'Multiplex' 'Sandwich Place'
 'Latin American Restaurant' 'Sporting Goods Shop' 'Bar' 'Bistro'
 'Roof Deck' 'Indian Restaurant' 'Ice Cream Shop' 'Gym / Fitness Center'
 'Asian Restaurant' 'Outlet Mall' 'Hotel Bar' 'Post Office'
 'Bubble Tea Shop' 'Pedestrian Plaza' 'Sports Bar' 'Music Store'
 'Outlet Store' 'Electronics Store' 'Train Station' 'Diner'
 'Kitchen Supply Store' 'Seafood Restaurant' 'Lounge' 'Fish Market'
 'Kebab Restaurant' 'Gelato Shop' 'Turkish Restaurant' 'Bookstore'
 'Donut Shop' 'Irish Pub' 'Sushi Restaurant' 'Gastropub' 'Movie Theater'
 'Cricket Ground' 'Auto Garage' 'Bridal Shop' 'Business Service' 'Gym'
 'Museum' 'Gift Shop' 'Dessert Shop' 'Breakfast Spot'
 'Modern European Restaurant' 'Art Gallery' 'Juice Bar' 'Malay Restaurant'
 'Market' 'Thai Restaurant' 'Garden' 'Escape Room' 'Deli / Bodega'
 'Event Space' 'Speakeasy' 'Tapas Restaurant' 'Beer Bar'
 'Middle Eastern Restaurant' 'Film Studio' 'Science Museum' 'Canal'
 'Vegetarian / Vegan Restaurant' 'Shopping Plaza' 'Library' 'Steakhouse'
 'Cocktail Bar' 'Canal Lock' 'Sri Lankan Restaurant' 'Church'
 'Street Food Gathering' 'Wine Bar' 'History Museum' 'Gaming Cafe'
 'Spanish Restaurant' 'Korean Restaurant' 'Caribbean Restaurant'
 'Burrito Place' 'Brewery' 'Stationery Store' 'Newsagent'
 'French Restaurant' 'Insurance Office' 'Platform' 'Tram Station'
 'Photography Studio' 'Vietnamese Restaurant' 'Theater' 'Salad Place'
 'Organic Grocery' 'Noodle House' 'Ramen Restaurant' 'Persian Restaurant'
 'Performing Arts Venue' 'Polish Restaurant' 'Doner Restaurant'
 'Bagel Shop' 'English Restaurant' 'Hookah Bar' 'Optical Shop'
 'Outdoor Supply Store' 'Wine Shop' 'Discount Store' 'African Restaurant'
 'Flea Market' 'Child Care Service' 'Tunnel' 'Pier' 'Fountain'
 'Boat or Ferry' 'River' 'Pool' 'Beer Store' 'Creperie' 'Historic Site'
 'Butcher' 'Taiwanese Restaurant' 'Japanese Restaurant'
 'Argentinian Restaurant' 'Record Shop' 'Food & Drink Shop'
 'Recording Studio' 'Garden Center' 'Food Truck' 'Boarding House'
 'Jazz Club' 'Concert Hall' 'Gourmet Shop' 'Track Stadium' 'Food'
 'South Indian Restaurant' 'Soccer Field' 'Afghan Restaurant'
 'Brazilian Restaurant' 'Casino' 'Cosmetics Shop' 'Toy / Game Store'
 'Mobile Phone Shop' 'Metro Station' 'Hostel' 'Health Food Store'
 'Gay Bar' 'Liquor Store' 'Boutique' 'Tiki Bar' 'Yoga Studio' 'Hobby Shop'
 'Arts & Crafts Store' 'Trail' 'Hunan Restaurant' 'Cheese Shop' 'Spa'
 'Austrian Restaurant' 'Cupcake Shop' 'Tea Room' 'Tennis Court'
 'Nail Salon' 'Opera House' 'Palace' 'Pilates Studio' 'Exhibit'
 'Farmers Market' 'German Restaurant' 'Cajun / Creole Restaurant'
 'Rock Club' 'Public Art' 'Souvlaki Shop' 'Falafel Restaurant'
 'Smoothie Shop' 'Indie Movie Theater' 'Okonomiyaki Restaurant'
 'Street Art' 'New American Restaurant' 'BBQ Joint' 'Dumpling Restaurant'
 'South American Restaurant' 'Dim Sum Restaurant' 'Winery' 'Champagne Bar'
 'Social Club' 'Windmill' 'Cantonese Restaurant' 'Hardware Store' 'Tree'
 'Pet Store' 'Rafting' 'Airport' 'Airport Service' 'Airport Lounge'
 'Duty-free Shop' 'Border Crossing' 'Airport Ticket Counter'
 'Light Rail Station' 'Farm' 'Buffet' 'Beer Garden' 'Comedy Club'
 'Athletics & Sports' 'Scenic Lookout' 'Road' 'Castle' 'Distillery'
 'Food Stand' 'Empanada Restaurant' 'Bike Shop' 'Herbs & Spices Store'
 'Monument / Landmark' 'Soccer Stadium' 'Nature Preserve' 'Poke Place'
 'Cycle Studio' 'Convenience Store' 'Fried Chicken Joint'
 'Harbor / Marina' 'Thrift / Vintage Store' 'Lebanese Restaurant'
 'Mini Golf' 'Chaat Place' 'Art Museum' 'Australian Restaurant'
 'Camera Store']

In [20]:
# Separating out the 'East Asian' types of restaurants
east_asian_cuisine = ["Chinese Restaurant", "Asian Restaurant", "Sushi Restaurant", "Korean Restaurant", 
                      "Noodle House", "Ramen Restaurant", "Taiwanese Restaurant", "Japanese Restaurant", 
                      "Hunan Restaurant", "Okonomiyaki Restaurant", "Dumpling Restaurant", "Dim Sum Restaurant", 
                      "Cantonese Restaurant"]

In [21]:
# One hot encoding each venue type for each Borough
london_onehot = pd.get_dummies(london_venues[["Venue Category"]], prefix = "", prefix_sep = "")

# Adding the Borough column to the new Dataframe
london_onehot["Borough"] = london_venues["Borough"]

# Re-ordering the columns to make sure the Borough column is first in the Dataframe
fixed_columns = [london_onehot.columns[-1]] + list(london_onehot.columns[:-1])
london_onehot = london_onehot[fixed_columns]

london_onehot

,Borough,Afghan Restaurant,African Restaurant,Airport,Airport Lounge,Airport Service,Airport Ticket Counter,American Restaurant,Argentinian Restaurant,Art Gallery,...,Turkish Restaurant,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Warehouse Store,Windmill,Wine Bar,Wine Shop,Winery,Yoga Studio
0,Barnet,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Barnet,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Barnet,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Barnet,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Barnet,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2188,Westminster,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2189,Westminster,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2190,Westminster,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2191,Westminster,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2192,Westminster,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
# Grouping the rows by Borough and taking the mean of the frequency of each category
london_grouped = london_onehot.groupby(["Borough"]).mean().reset_index()
london_grouped

,Borough,Afghan Restaurant,African Restaurant,Airport,Airport Lounge,Airport Service,Airport Ticket Counter,American Restaurant,Argentinian Restaurant,Art Gallery,...,Turkish Restaurant,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Warehouse Store,Windmill,Wine Bar,Wine Shop,Winery,Yoga Studio
0,Barnet,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
1,Bexley,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.042553,0.000000,0.000000,...,0.000000,0.000000,0.021277,0.000000,0.021277,0.00,0.00,0.000000,0.00,0.000000
2,Brent,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.022222,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.011111,0.00,0.00,0.000000,0.00,0.000000
3,Bromley,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.016129,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
4,Camden,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020000,...,0.010000,0.010000,0.000000,0.000000,0.000000,0.00,0.01,0.000000,0.00,0.000000
5,Croydon,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.010417,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
6,Ealing,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,...,0.010000,0.000000,0.010000,0.020000,0.000000,0.00,0.01,0.000000,0.00,0.000000
7,Enfield,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.015873,0.000000,0.015873,0.000000,0.000000,0.00,0.00,0.015873,0.00,0.000000
8,Greenwich,0.00000,0.017241,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.017241,0.017241,0.00,0.00,0.000000,0.00,0.000000
9,Hackney,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012658,0.000000,...,0.000000,0.012658,0.000000,0.012658,0.000000,0.00,0.00,0.012658,0.00,0.000000
10,Hammersmith and Fulham,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.010000,0.010000,0.000000,0.010000,0.000000,0.00,0.00,0.000000,0.00,0.000000
11,Haringey,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.058824,0.000000,0.014706,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
12,Harrow,0.02381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
13,Havering,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.026316,0.000000,0.000000,...,0.013158,0.000000,0.013158,0.000000,0.013158,0.00,0.00,0.013158,0.00,0.000000
14,Hillingdon,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.013889,0.000000,0.000000,0.000000,0.013889,0.00,0.00,0.000000,0.00,0.000000
15,Hounslow,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.015152,0.000000,0.015152,0.00,0.00,0.000000,0.00,0.000000
16,Islington,0.01000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.010000
17,Kensington and Chelsea,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.01,0.000000,0.00,0.020000
18,Kingston upon Thames,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.010000,0.010000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
19,Lambeth,0.00000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,...,0.000000,0.010000,0.000000,0.000000,0.000000,0.01,0.01,0.000000,0.01,0.020000
20,Lewisham,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.025641,0.00,0.00,0.000000,0.00,0.000000
21,Merton,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
22,Newham,0.00000,0.000000,0.026316,0.026316,0.026316,0.026316,0.026316,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
23,Redbridge,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.044444,0.000000,0.000000,0.000000,0.022222,0.00,0.00,0.000000,0.00,0.000000
24,Richmond upon Thames,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012987,...,0.000000,0.000000,0.000000,0.012987,0.000000,0.00,0.00,0.012987,0.00,0.000000
25,Southwark,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,0.010000,0.010000,...,0.000000,0.000000,0.000000,0.010000,0.000000,0.00,0.01,0.000000,0.00,0.000000
26,Sutton,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.019608,0.000000,0.019608,0.00,0.00,0.000000,0.00,0.000000
27,Tower Hamlets,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
28,Waltham Forest,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051282,...,0.025641,0.025641,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.000000
29,Wandsworth,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.00,0.013333
30,Westminster,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.010000,0.000000,0.000000,0.000000,0.000000,0.00,0.01,0.000000,0.00,0.000000

In [23]:
# Creating a new Dataframe containing just the 'East Asian' restaurants in each Borough
london_asian_restaurants = london_grouped[["Borough", "Asian Restaurant", "Cantonese Restaurant", "Chinese Restaurant", 
                                           "Dim Sum Restaurant", "Dumpling Restaurant", "Hunan Restaurant", 
                                           "Japanese Restaurant", "Korean Restaurant", "Noodle House", "Okonomiyaki Restaurant",
                                           "Ramen Restaurant", "Sushi Restaurant", "Taiwanese Restaurant"]]
london_asian_restaurants

,Borough,Asian Restaurant,Cantonese Restaurant,Chinese Restaurant,Dim Sum Restaurant,Dumpling Restaurant,Hunan Restaurant,Japanese Restaurant,Korean Restaurant,Noodle House,Okonomiyaki Restaurant,Ramen Restaurant,Sushi Restaurant,Taiwanese Restaurant
0,Barnet,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
1,Bexley,0.000000,0.00,0.021277,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
2,Brent,0.011111,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
3,Bromley,0.016129,0.00,0.016129,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.016129,0.000000
4,Camden,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.010000,0.000000
5,Croydon,0.020833,0.00,0.010417,0.00,0.00,0.00,0.000000,0.020833,0.00,0.00,0.000000,0.010417,0.000000
6,Ealing,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.01,0.00,0.010000,0.010000,0.000000
7,Enfield,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
8,Greenwich,0.017241,0.00,0.017241,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
9,Hackney,0.000000,0.00,0.000000,0.00,0.00,0.00,0.012658,0.000000,0.00,0.00,0.012658,0.000000,0.012658
10,Hammersmith and Fulham,0.010000,0.00,0.000000,0.00,0.00,0.00,0.030000,0.000000,0.00,0.00,0.000000,0.010000,0.000000
11,Haringey,0.000000,0.00,0.044118,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
12,Harrow,0.000000,0.00,0.023810,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
13,Havering,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
14,Hillingdon,0.013889,0.00,0.013889,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
15,Hounslow,0.015152,0.00,0.015152,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
16,Islington,0.000000,0.00,0.000000,0.00,0.00,0.01,0.010000,0.000000,0.00,0.00,0.000000,0.020000,0.000000
17,Kensington and Chelsea,0.010000,0.00,0.020000,0.00,0.00,0.00,0.010000,0.000000,0.00,0.00,0.000000,0.010000,0.000000
18,Kingston upon Thames,0.010000,0.00,0.010000,0.00,0.00,0.00,0.020000,0.000000,0.00,0.00,0.000000,0.030000,0.000000
19,Lambeth,0.000000,0.01,0.000000,0.01,0.01,0.00,0.020000,0.000000,0.00,0.01,0.010000,0.000000,0.000000
20,Lewisham,0.000000,0.00,0.025641,0.00,0.00,0.00,0.025641,0.000000,0.00,0.00,0.000000,0.000000,0.000000
21,Merton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.034483,0.000000,0.00,0.00,0.000000,0.000000,0.000000
22,Newham,0.000000,0.00,0.026316,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
23,Redbridge,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
24,Richmond upon Thames,0.000000,0.00,0.012987,0.00,0.00,0.00,0.012987,0.000000,0.00,0.00,0.000000,0.000000,0.000000
25,Southwark,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
26,Sutton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
27,Tower Hamlets,0.000000,0.00,0.013699,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.013699,0.013699,0.000000
28,Waltham Forest,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
29,Wandsworth,0.026667,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000
30,Westminster,0.000000,0.00,0.010000,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.000000,0.020000,0.000000

In [24]:
# Summing up all the frequencies in each Borough
summed_restaurants = london_asian_restaurants.sum(axis = 1)
summed_restaurants

0     0.000000
1     0.021277
2     0.011111
3     0.048387
4     0.020000
5     0.062500
6     0.040000
7     0.000000
8     0.034483
9     0.037975
10    0.050000
11    0.044118
12    0.023810
13    0.000000
14    0.027778
15    0.030303
16    0.040000
17    0.050000
18    0.070000
19    0.070000
20    0.051282
21    0.034483
22    0.026316
23    0.000000
24    0.025974
25    0.010000
26    0.000000
27    0.041096
28    0.000000
29    0.026667
30    0.040000
dtype: float64

In [25]:
# Adding the summed values to the main Dataframe
london_asian_restaurants["Total"] = summed_restaurants
london_asian_restaurants

,Borough,Asian Restaurant,Cantonese Restaurant,Chinese Restaurant,Dim Sum Restaurant,Dumpling Restaurant,Hunan Restaurant,Japanese Restaurant,Korean Restaurant,Noodle House,Okonomiyaki Restaurant,Ramen Restaurant,Sushi Restaurant,Taiwanese Restaurant,Total
0,Barnet,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
1,Bexley,0.000000,0.00,0.021277,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.021277
2,Brent,0.011111,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.011111
3,Bromley,0.016129,0.00,0.016129,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.016129,0.000000,0.048387
4,Camden,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.020000
5,Croydon,0.020833,0.00,0.010417,0.00,0.00,0.00,0.000000,0.020833,0.00,0.00,0.000000,0.010417,0.000000,0.062500
6,Ealing,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.01,0.00,0.010000,0.010000,0.000000,0.040000
7,Enfield,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
8,Greenwich,0.017241,0.00,0.017241,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.034483
9,Hackney,0.000000,0.00,0.000000,0.00,0.00,0.00,0.012658,0.000000,0.00,0.00,0.012658,0.000000,0.012658,0.037975
10,Hammersmith and Fulham,0.010000,0.00,0.000000,0.00,0.00,0.00,0.030000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.050000
11,Haringey,0.000000,0.00,0.044118,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.044118
12,Harrow,0.000000,0.00,0.023810,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.023810
13,Havering,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
14,Hillingdon,0.013889,0.00,0.013889,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.027778
15,Hounslow,0.015152,0.00,0.015152,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.030303
16,Islington,0.000000,0.00,0.000000,0.00,0.00,0.01,0.010000,0.000000,0.00,0.00,0.000000,0.020000,0.000000,0.040000
17,Kensington and Chelsea,0.010000,0.00,0.020000,0.00,0.00,0.00,0.010000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.050000
18,Kingston upon Thames,0.010000,0.00,0.010000,0.00,0.00,0.00,0.020000,0.000000,0.00,0.00,0.000000,0.030000,0.000000,0.070000
19,Lambeth,0.000000,0.01,0.000000,0.01,0.01,0.00,0.020000,0.000000,0.00,0.01,0.010000,0.000000,0.000000,0.070000
20,Lewisham,0.000000,0.00,0.025641,0.00,0.00,0.00,0.025641,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.051282
21,Merton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.034483,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.034483
22,Newham,0.000000,0.00,0.026316,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.026316
23,Redbridge,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
24,Richmond upon Thames,0.000000,0.00,0.012987,0.00,0.00,0.00,0.012987,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.025974
25,Southwark,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.010000
26,Sutton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
27,Tower Hamlets,0.000000,0.00,0.013699,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.013699,0.013699,0.000000,0.041096
28,Waltham Forest,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
29,Wandsworth,0.026667,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.026667
30,Westminster,0.000000,0.00,0.010000,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.000000,0.020000,0.000000,0.040000

In [26]:
# Sorting the Dataframe so the Boroughs with the highest frequency of 'East Asian' restaurants are at the top
sorted_restaurants = london_asian_restaurants.sort_values(by = ["Total"], ascending = False, ignore_index = True)
sorted_restaurants

,Borough,Asian Restaurant,Cantonese Restaurant,Chinese Restaurant,Dim Sum Restaurant,Dumpling Restaurant,Hunan Restaurant,Japanese Restaurant,Korean Restaurant,Noodle House,Okonomiyaki Restaurant,Ramen Restaurant,Sushi Restaurant,Taiwanese Restaurant,Total
0,Lambeth,0.000000,0.01,0.000000,0.01,0.01,0.00,0.020000,0.000000,0.00,0.01,0.010000,0.000000,0.000000,0.070000
1,Kingston upon Thames,0.010000,0.00,0.010000,0.00,0.00,0.00,0.020000,0.000000,0.00,0.00,0.000000,0.030000,0.000000,0.070000
2,Croydon,0.020833,0.00,0.010417,0.00,0.00,0.00,0.000000,0.020833,0.00,0.00,0.000000,0.010417,0.000000,0.062500
3,Lewisham,0.000000,0.00,0.025641,0.00,0.00,0.00,0.025641,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.051282
4,Hammersmith and Fulham,0.010000,0.00,0.000000,0.00,0.00,0.00,0.030000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.050000
5,Kensington and Chelsea,0.010000,0.00,0.020000,0.00,0.00,0.00,0.010000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.050000
6,Bromley,0.016129,0.00,0.016129,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.016129,0.000000,0.048387
7,Haringey,0.000000,0.00,0.044118,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.044118
8,Tower Hamlets,0.000000,0.00,0.013699,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.013699,0.013699,0.000000,0.041096
9,Westminster,0.000000,0.00,0.010000,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.000000,0.020000,0.000000,0.040000
10,Islington,0.000000,0.00,0.000000,0.00,0.00,0.01,0.010000,0.000000,0.00,0.00,0.000000,0.020000,0.000000,0.040000
11,Ealing,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.01,0.00,0.010000,0.010000,0.000000,0.040000
12,Hackney,0.000000,0.00,0.000000,0.00,0.00,0.00,0.012658,0.000000,0.00,0.00,0.012658,0.000000,0.012658,0.037975
13,Merton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.034483,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.034483
14,Greenwich,0.017241,0.00,0.017241,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.034483
15,Hounslow,0.015152,0.00,0.015152,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.030303
16,Hillingdon,0.013889,0.00,0.013889,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.027778
17,Wandsworth,0.026667,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.026667
18,Newham,0.000000,0.00,0.026316,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.026316
19,Richmond upon Thames,0.000000,0.00,0.012987,0.00,0.00,0.00,0.012987,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.025974
20,Harrow,0.000000,0.00,0.023810,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.023810
21,Bexley,0.000000,0.00,0.021277,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.021277
22,Camden,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.020000
23,Brent,0.011111,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.011111
24,Southwark,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.010000
25,Havering,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
26,Enfield,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
27,Redbridge,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
28,Sutton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
29,Waltham Forest,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
30,Barnet,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000

This Dataframe shows that the Boroughs with the highest proportion of 'East Asian' restaurants are Lambeth and Kingston upon Thames, both with a frequency of 0.07, followed by Croydon and Lewisham (0.0625 and 0.0513 respectively).

In [27]:
# Sorting the Dataframe so the Boroughs with the highest frequency of Korean restaurants are at the top
sorted_restaurants_korean = london_asian_restaurants.sort_values(by = ["Korean Restaurant"], ascending = False, 
                                                                 ignore_index = True)
sorted_restaurants_korean

,Borough,Asian Restaurant,Cantonese Restaurant,Chinese Restaurant,Dim Sum Restaurant,Dumpling Restaurant,Hunan Restaurant,Japanese Restaurant,Korean Restaurant,Noodle House,Okonomiyaki Restaurant,Ramen Restaurant,Sushi Restaurant,Taiwanese Restaurant,Total
0,Croydon,0.020833,0.00,0.010417,0.00,0.00,0.00,0.000000,0.020833,0.00,0.00,0.000000,0.010417,0.000000,0.062500
1,Westminster,0.000000,0.00,0.010000,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.000000,0.020000,0.000000,0.040000
2,Islington,0.000000,0.00,0.000000,0.00,0.00,0.01,0.010000,0.000000,0.00,0.00,0.000000,0.020000,0.000000,0.040000
3,Wandsworth,0.026667,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.026667
4,Waltham Forest,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
5,Tower Hamlets,0.000000,0.00,0.013699,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.013699,0.013699,0.000000,0.041096
6,Sutton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
7,Southwark,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.010000
8,Richmond upon Thames,0.000000,0.00,0.012987,0.00,0.00,0.00,0.012987,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.025974
9,Redbridge,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
10,Newham,0.000000,0.00,0.026316,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.026316
11,Merton,0.000000,0.00,0.000000,0.00,0.00,0.00,0.034483,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.034483
12,Lewisham,0.000000,0.00,0.025641,0.00,0.00,0.00,0.025641,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.051282
13,Lambeth,0.000000,0.01,0.000000,0.01,0.01,0.00,0.020000,0.000000,0.00,0.01,0.010000,0.000000,0.000000,0.070000
14,Kingston upon Thames,0.010000,0.00,0.010000,0.00,0.00,0.00,0.020000,0.000000,0.00,0.00,0.000000,0.030000,0.000000,0.070000
15,Kensington and Chelsea,0.010000,0.00,0.020000,0.00,0.00,0.00,0.010000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.050000
16,Barnet,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
17,Bexley,0.000000,0.00,0.021277,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.021277
18,Hillingdon,0.013889,0.00,0.013889,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.027778
19,Havering,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
20,Harrow,0.000000,0.00,0.023810,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.023810
21,Haringey,0.000000,0.00,0.044118,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.044118
22,Hammersmith and Fulham,0.010000,0.00,0.000000,0.00,0.00,0.00,0.030000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.050000
23,Hackney,0.000000,0.00,0.000000,0.00,0.00,0.00,0.012658,0.000000,0.00,0.00,0.012658,0.000000,0.012658,0.037975
24,Greenwich,0.017241,0.00,0.017241,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.034483
25,Enfield,0.000000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.000000
26,Ealing,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.01,0.00,0.010000,0.010000,0.000000,0.040000
27,Camden,0.010000,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.010000,0.000000,0.020000
28,Bromley,0.016129,0.00,0.016129,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.016129,0.000000,0.048387
29,Brent,0.011111,0.00,0.000000,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.011111
30,Hounslow,0.015152,0.00,0.015152,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.000000,0.030303

This Dataframe shows that only two Boroughs have Korean restaurants, with Croydon having a frequency of 0.0208 and Westminster having a frequency of 0.01.